spring:
  application:
    name: eureka-server


server:
  port: ${PORT:8761}


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    eviction-interval-timer-in-ms: 50000


